"""test module for huffman encoding
   runs encoding on randomly generated byte strings"""

from random import randrange
from huffman_code import HuffmanCode
import unittest



class test(unittest.TestCase):

    def setUp(self, n_tests=1000, w_size=100):
        self.num_errors = 0  # number of errors
        self.num_tests = n_tests  # number of words to encode and decode
        self.word_size = w_size  # default size of the generated words

    def test_generate_encode_decode(self):
        # randomly generate words, encode and decode them
        errors = []
        for _ in range(self.num_tests):
            word = "".join([chr(randrange(1, 50)) for _ in range(self.word_size)])
            a = HuffmanCode(word)
            returned_word = a.decode(a.encode(word))
            self.assertEqual(str.encode(word), returned_word)




if __name__ == "__main__":
    unittest.main()